import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTopBtn from "@/components/ScrollToTopBtn";
import SideNavbar from "@/components/SideNavbar";

export const metadata: Metadata = {
  title: "GameHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className="min-h-screen flex flex-col">
  <Navbar />

  <div>
    <SideNavbar />
    <main>
      <ScrollToTopBtn />
      {children}
    </main>
  </div>

  <Footer />
</body>
    </html>
  );
}
