import type { Metadata } from "next";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTopBtn from "@/components/ScrollToTopBtn";
import SideNavbar from "@/components/NavbarSidebar";
import AdminSidebar from "@/components/AdminSidebar";
import NavbarSidebar from "@/components/NavbarSidebar";

export const metadata: Metadata = {
  title: "GameHub",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    

<div className="min-h-screen flex flex-col">
      <Navbar />
      <div className="flex">
        <NavbarSidebar />
        <main className="w-full">
          <ScrollToTopBtn />
          {children}
        </main>
      </div>
      <Footer />
    </div>
  
  );
}
